name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: installs graphviz
        run: |
          sudo apt-get install graphviz

      - name: npm install and build
        run: |
          npm ci
          npm install
          npm run build:ts
        env:
          CI: true

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.3.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORT_ID }}
        with:
          coverageCommand: npm test
          debug: true
